
name: Publish Packets Exporter
on: [release]
jobs:
  push-manifest:
    runs-on: [ubuntu-latest]
    steps:
      - name: setup docker(Without version)
        uses: docker-practice/actions-setup-docker@master
      - run: |
          docker manifest create efrat19/packets-exporter:stable efrat19/packets-exporter:arm-${{ github.sha }} efrat19/packets-exporter:amd64-${{ github.sha }}
          docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker manifest push efrat19/packets-exporter:stable
